### ISSUE TITLE
Reconcile which repos belong here

### ISSUE THREAD

**Issue by hauten** [LLNL/radiuss#34]
Comparing sources of truth:

- software.llnl.gov/explore/#/RADIUSS – has two Hatchets (LLNL org, hatchet org); has radiuss-ci, radiuss, radiuss-spack-testing (I understand why these would not be in this new repo)
- this repo – missing: spot2_container, spotfe, spotbe, b-mpi3
- LC Confluence RADIUSS home – lists all spot repos, b-mpi3, & hatchet/hatchet

Questions for this repo specifically:

- Should these be added: spot2_container, spotfe, spotbe, b-mpi3
- Should LLNL/hatchet change to hatchet/hatchet

**Comment by vsoch** [comment]
Thank you for opening this!

>software.llnl.gov/explore/#/RADIUSS – has two Hatchets (LLNL org, hatchet org); has radiuss-ci, radiuss, radiuss-spack-testing (I understand why these would not be in this new repo)

I noticed this too - and I think there was some internal drama, and that the llnl version of hatchet is the "correct' one still maintained by the lab because hatchet/hatchet was created by the guy that left the lab (and doesn't want to support what the lab needs)

> this repo – missing: spot2_container, spotfe, spotbe, b-mpi3

I had only chose to add "the main" spot to reduce redundancy. Can you share GitHub links to these missing projects?

**Comment by hauten** [comment]
Gotcha, makes sense re: hatchet. Spots et al:
https://github.com/LLNL/spotbe
https://github.com/LLNL/spotfe
https://github.com/LLNL/spot2_container
https://github.com/LLNL/b-mpi3

**Comment by vsoch** [comment]
okay I'll add them asap!

**Comment by vsoch** [comment]
All I need to do is add them to the contributor-ci.yaml, but since we might want to discuss custom logos, etc, what I'll do is add them, run the contributor-ci command locally (generates the data) and then open a PR for us to discuss! I will ping you soon!

**Comment by vsoch** [comment]
All set here. Thanks again @hauten !
